### ISSUE TITLE
Add Extra End Note in Translating From ORMs to Active Record Lab

### ISSUE THREAD

**Issue by arnold805** [learn-co-curriculum/phase-3-active-record-translating-from-orm-to-ar#4]
### Canvas Link

https://learning.flatironschool.com/courses/4567/assignments/165858?module_item_id=357798

### Concern

this lecture gave instruction to do the simple task of adding in ActiveRecord::Base to the Dog class, and thus passes all of the tests. At first I wasn't sure why until I mentioned it to my instructor. His response: "it’s illustrating that by inheriting from that module, all of those methods automatically will be defined for your Dog class".

Maybe adding in a similar note to the end of this lab would be useful to eliminate some confusion or hesitation about tests passing in a false positive reason.

### Suggested Changes

This illustrates that by inheriting from that module, all of many methods are automatically defined for your Dog class.

**Comment by graciemcguire** [comment]
Hi @arnold805!

Thank you for your feedback! We'll take this suggestion into consideration in
upcoming releases of this curriculum.

As always, thanks for contributing! 💙
